Exception on /regist [POST]
Traceback (most recent call last):
  File "C:\Users\220063\AppData\Local\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\220063\AppData\Local\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\220063\AppData\Local\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\220063\AppData\Local\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\220063\AppData\Local\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\220063\AppData\Local\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\220063\Desktop\松坂侑隼\ソフト\話題提供\communication\blueprint\Chat.py", line 347, in regist
    c.execute("insert into user values(null,?,?,?)", (name, password,name))
sqlite3.OperationalError: table user has 3 columns but 4 values were supplied
Exception on /login2 [POST]
Traceback (most recent call last):
  File "C:\Users\220063\AppData\Local\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\220063\AppData\Local\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\220063\AppData\Local\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\220063\AppData\Local\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\220063\AppData\Local\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\220063\AppData\Local\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\220063\Desktop\松坂侑隼\ソフト\話題提供\communication\blueprint\Chat.py", line 289, in login
    c.execute(
sqlite3.OperationalError: no such column: nickname
